# Generated by Django 5.1.6 on 2025-02-22 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadEquip', '0003_equipamento_horimetro_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('horimetro', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp_devices', to='CadEquip.equipamento')),
            ],
        ),
    ]
