# Generated by Django 5.1.6 on 2025-02-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadEquip', '0003_equipamento_horimetro_atual_and_more'),
        ('monitorESP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32device',
            name='atualizacao_automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esp32device',
            name='horimetro_offset',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='esp32device',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esp_devices', to='CadEquip.equipamento'),
        ),
    ]
