# Generated by Django 5.1.1 on 2025-01-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadFornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('localizacao', models.CharField(help_text='Localização física no estoque', max_length=100)),
                ('data_ultima_compra', models.DateField(null=True)),
                ('vida_util', models.IntegerField(help_text='Vida útil em dias', null=True)),
                ('orcamentos', models.FileField(blank=True, null=True, upload_to='orcamentos/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_pecas/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas', to='CadFornecedor.fornecedor')),
            ],
        ),
    ]
