# Generated by Django 5.1.1 on 2025-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=200)),
                ('fornecedor_fone', models.CharField(max_length=200)),
                ('fornecedor_site', models.CharField(blank=True, max_length=200, null=True)),
                ('fornecedor_email', models.CharField(blank=True, max_length=200, null=True)),
                ('rua', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
                ('contato', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=200, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('prazo_entrega_medio', models.IntegerField(help_text='Prazo médio em dias', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
