# Generated by Django 5.1.1 on 2025-01-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadFornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200, unique=True)),
                ('patrimonio', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('modelo', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('ano_fabricacao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_equipamentos/%Y/%m/%d/')),
                ('manual_operacao', models.FileField(blank=True, null=True, upload_to='manuais/')),
                ('garantia_termino', models.DateField(blank=True, null=True)),
                ('classe', models.CharField(blank=True, max_length=1, null=True)),
                ('ssma', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='c', max_length=1)),
                ('qualidade', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='c', max_length=1)),
                ('operacao', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='c', max_length=1)),
                ('entrega', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='c', max_length=1)),
                ('mtbf', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='c', max_length=1)),
                ('mttr', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='c', max_length=1)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='CadFornecedor.fornecedor')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
