# Generated by Django 5.1.1 on 2025-01-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadEquip', '0001_initial'),
        ('gestaoOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='gestaoOS.setor'),
        ),
    ]
