# Generated by Django 5.1.1 on 2025-01-29 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadEquip', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='horimetro_atual',
            field=models.FloatField(default=0, help_text='Horas totais de operação do equipamento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoHorasMensais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(help_text='Ano do registro')),
                ('mes', models.IntegerField(help_text='Mês do registro (1 a 12)')),
                ('horas_trabalhadas', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_horas_mensais', to='CadEquip.equipamento')),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('equipamento', 'ano', 'mes')},
            },
        ),
    ]
