# Generated by Django 5.1.1 on 2025-01-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadEquip', '0001_initial'),
        ('cadEstoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calculo', models.CharField(choices=[('horas', 'Horas'), ('meses', 'Meses'), ('ambos', 'Ambos')], max_length=100)),
                ('requer_parada', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('em_execucao', 'Em Execução'), ('atrasada', 'Atrasada')], default='Programada', max_length=50)),
                ('duracao_estimada', models.FloatField(help_text='Duração estimada em horas', null=True)),
                ('duracao_real', models.FloatField(help_text='Duração real em horas', null=True)),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
                ('data_proxima_manutencao', models.DateField(blank=True, null=True)),
                ('horimetro_atual', models.FloatField(blank=True, null=True)),
                ('media_horas', models.FloatField(blank=True, null=True)),
                ('periodo_meses', models.IntegerField(blank=True, null=True)),
                ('horas_intervalo', models.FloatField(blank=True, null=True)),
                ('procedimentos', models.FileField(blank=True, null=True, upload_to='procedimento_pdfs/')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='CadEquip.equipamento')),
                ('pecas', models.ManyToManyField(blank=True, related_name='manutencoes', to='cadEstoque.pecas')),
            ],
        ),
        migrations.CreateModel(
            name='PecasManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_necessarias', to='GestaoPrev.manutencaopreventiva')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes_necessarias', to='cadEstoque.pecas')),
            ],
        ),
    ]
