# Generated by Django 5.1.1 on 2025-01-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoPrev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencaopreventiva',
            name='media_horas',
        ),
    ]
