"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w24e=3w=s4-4yl38@imz$d)sq0d+#%agh$jh7d6_ziva!e0vkz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestaoUsuarios',
    'gestaoOS',
    'cadEstoque',
    'CadEquip',
    'CadFornecedor',
    'GestaoPrev',
    'gestao_usuarios_admin',
    'relatorios',
    'monitorESP',
    'bootstrap4',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('NAME',''),    # dbsoftwareweconn
        'USER': os.environ.get('USER',''),    # dvweconn
        'PASSWORD': os.environ.get('PASSWORD',''), # dvweconn12345
        'HOST': os.environ.get('HOST',''),      #  database-3.c7s2qek46af6.sa-east-1.rds.amazonaws.com
        'PORT': '5432',
    }
}
'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dbsoftwareweconn',    # dbsoftwareweconn
        'USER': 'dvweconn',    # dvweconn
        'PASSWORD': 'dvweconn12345', # dvweconn12345
        'HOST': 'database-3.c7s2qek46af6.sa-east-1.rds.amazonaws.com',      #  database-3.c7s2qek46af6.sa-east-1.rds.amazonaws.com
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Se você estiver no ambiente de desenvolvimento, certifique-se de que Django pode servir arquivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Local onde o diretório static está
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configurações de integração com Weconn
WECONN_API_KEY = '3qpc1TGv.Zy5j95o6mrrxF8ZBiZCbkFATmWMvYRy2'  # Substituir pela chave real
WECONN_BASE_URL = 'http://siteweconn-dev.sa-east-1.elasticbeanstalk.com'
WECONN_TENANT_SLUG = 'PikeOViking'  # Substituir pelo slug do tenant

# Tempo de expiração do cache para informações do tenant (em segundos)
WECONN_CACHE_TIMEOUT = 1800  # 30 minutos


# Amazon S3 configuration

# AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID','')
# AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY','')


# AWS_STORAGE_BUCKET_NAME = 'estaticossoftwaregestao'

# Django 4.2 > 
# STORAGES = {"staticfiles": {"BACKEND": "storages.backends.s3boto3.S3StaticStorage"}}

# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
