# Generated by Django 5.1.1 on 2025-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('grupo', models.CharField(choices=[('Solicitante', 'Solicitante'), ('Técnico', 'Técnico'), ('Estoquista', 'Estoquista'), ('Gestor', 'Gestor')], default='Solicitante', max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
