# Generated by Django 5.1.1 on 2025-01-17 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadEquip', '0001_initial'),
        ('cadEstoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('duracao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Duração (em horas)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='acoes_pdfs/')),
                ('colaboradores', models.ManyToManyField(limit_choices_to={'groups__name': 'Técnico'}, to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='AcaoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_pecas', to='gestaoOS.acao')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadEstoque.pecas')),
            ],
        ),
        migrations.AddField(
            model_name='acao',
            name='pecas_utilizadas',
            field=models.ManyToManyField(blank=True, related_name='AcoesPecas', through='gestaoOS.AcaoPeca', to='cadEstoque.pecas'),
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('finalizado', 'finalizado'), ('concluido', 'Concluído')], default='pendente', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tempo_parada', models.FloatField(help_text='Tempo de parada em horas', null=True)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('solucao', models.TextField(blank=True, null=True)),
                ('causa_raiz', models.TextField(blank=True, null=True)),
                ('data_inicio_atendimento', models.DateTimeField(null=True)),
                ('data_fim_atendimento', models.DateTimeField(null=True)),
                ('tipo_manutencao', models.CharField(choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva'), ('melhoria', 'Melhoria')], default='corretiva', max_length=20)),
                ('local', models.CharField(blank=True, max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_chamados/')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_equipamento', to='CadEquip.equipamento')),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Técnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico_chamados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor', to='gestaoOS.setor')),
            ],
        ),
        migrations.AddField(
            model_name='acao',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='gestaoOS.chamado'),
        ),
    ]
