# Generated by Django 5.1.1 on 2025-01-18 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoOS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='colaboradores',
        ),
        migrations.CreateModel(
            name='AcaoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas Trabalhadas')),
                ('descricao_atividade', models.TextField(verbose_name='Descrição da Atividade')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_colaboradores', to='gestaoOS.acao')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador da Ação',
                'verbose_name_plural': 'Colaboradores da Ação',
            },
        ),
    ]
